use book_store_2;
show tables;
desc books;
INSERT INTO books (book_title, book_author, book_price, book_description, book_image_link)
VALUES ("Harry Potter and the Chamber of Secrets", "J,K,Rowling", 10.50, "Summary
The three firm friends, Harry, Ron and Hermione, are soon immersed in the daily round of Potions, Herbology, Charms, Defence Against the Dark Arts, and Quidditch. But then horrible and mysterious things begin to happen. Harry keeps hearing strange voices, sinister and dark messages appear on the wall, and then Ron's sister Ginny disappears...", "https://m.media-amazon.com/images/I/81S0LnPGGUL.jpg");
INSERT INTO books (book_title, book_author, book_price, book_description, book_image_link)
VALUES ("To Kill a Mockingbird", "Harper Lee", 12.00, "To Kill a Mockingbird is a Pulitzer Prize-winning novel set in the Deep South during the Depression era. The story follows a young girl named Scout Finch as she grows up and learns about racial injustice in her community. Her father, a lawyer named Atticus Finch, defends a black man against an undeserved rape charge, and the trial reveals the prejudice and bigotry that permeate the town. The novel is a poignant examination of courage, morality, and the power of empathy.", "https://cdn.britannica.com/21/182021-050-666DB6B1/book-cover-To-Kill-a-Mockingbird-many-1961.jpg");
INSERT INTO books (book_title, book_author, book_price, book_description, book_image_link)
VALUES ("1984", "George Orwell", 9.50, "1984 is a dystopian classic set in a totalitarian state known as Oceania. The story follows the protagonist Winston Smith as he rebels against the oppressive government and falls in love with a fellow rebel named Julia. The novel explores themes of government surveillance, propaganda, and individual freedom, and has been praised for its prescience in predicting the dangers of authoritarianism.", "https://m.media-amazon.com/images/I/519zR2oIlmL.jpg");
INSERT INTO books (book_title, book_author, book_price, book_description, book_image_link)
VALUES ("Pride and Prejudice", "Jane Austen", 8.00, "Pride and Prejudice is a romance novel set in Georgian England. The story follows the independent-minded Elizabeth Bennet as she navigates the social expectations of her time and falls in love with the wealthy Mr. Darcy. Along the way, she must contend with societal pressures, family drama, and her own prejudices. The novel is a timeless examination of love, class, and gender roles.", "https://cdn.waterstones.com/bookjackets/large/9781/4351/9781435127449.jpg");
INSERT INTO books (book_title, book_author, book_price, book_description, book_image_link)
VALUES ("The Great Gatsby", "F. Scott Fitzgerald", 11.00, "The Great Gatsby is a classic American novel set in the 1920s. The story follows the mysterious millionaire Jay Gatsby as he throws extravagant parties in the hopes of winning back his lost love, Daisy Buchanan. Narrated by the disillusioned Nick Carraway, the novel explores themes of wealth, love, and the American Dream. The novel is a masterful portrait of the Jazz Age and a critique of the excesses of the era.", "https://kbimages1-a.akamaihd.net/5addc4c9-fbc1-42d7-a79f-cec7619d4b23/1200/1200/False/the-great-gatsby-a-novel-1.jpg");
INSERT INTO books (book_title, book_author, book_price, book_description, book_image_link)
VALUES ("The Catcher in the Rye", "J.D. Salinger", 9.00, "The Catcher in the Rye is a coming-of-age novel narrated by the troubled teenager Holden Caulfield. The novel follows Holden as he struggles to find meaning and connection in a world that he sees as phony and corrupt. Along the way, he encounters a cast of memorable characters and grapples with themes of alienation, innocence, and identity. The novel is a classic of 20th-century literature and a touchstone for generations of readers.", "https://m.media-amazon.com/images/I/91HPG31dTwL.jpg");
INSERT INTO books (book_title, book_author, book_price, book_description, book_image_link)
VALUES ("The Lord of the Rings", "J.R.R. Tolkien", 19.50, "The Lord of the Rings is an epic fantasy trilogy set in the fictional world of Middle-earth. The story follows hobbit Frodo Baggins as he embarks on a quest to destroy the One Ring, a powerful artifact that could enslave all of Middle-earth. Along the way, he is joined by a fellowship of diverse characters, including Gandalf the wizard, Aragorn the ranger, and Gimli the dwarf", "https://mrbsemporium.com/wp-content/uploads/2021/09/9780261103252.jpg");
INSERT INTO books (book_title, book_author, book_price, book_description, book_image_link)
VALUES ("The Handmaid's Tale", "Margaret Atwood", 13.00, "The Handmaid's Tale is a dystopian novel set in the near future. The story takes place in the Republic of Gilead, a totalitarian regime where women have been stripped of their rights and are valued only for their reproductive abilities. The novel follows the experiences of a handmaid named Offred as she navigates the oppressive society and searches for a way to regain her freedom. The novel has been praised for its exploration of gender, power, and the dangers of fundamentalism.", "https://m.media-amazon.com/images/I/61IGEzUA8YL.jpg");
INSERT INTO books (book_title, book_author, book_price, book_description, book_image_link)
VALUES ("The Picture of Dorian Gray", "Oscar Wilde", 9.50, "The Picture of Dorian Gray is a gothic novel that tells the story of a young man named Dorian Gray who becomes obsessed with his own beauty and youth. After having his portrait painted, Dorian makes a wish that he could remain young and handsome forever, while his portrait ages and shows the physical toll of his sins. As Dorian indulges in a life of decadence and debauchery, the portrait becomes increasingly grotesque. The novel is a haunting examination of vanity, corruption, and the consequences of unchecked desire.", "https://almabooks.com/wp-content/uploads/2016/10/9781847493729.jpg");
INSERT INTO books (book_title, book_author, book_price, book_description, book_image_link)
VALUES ("The Hitchhiker's Guide to the Galaxy", "Douglas Adams", 11.00, "The Hitchhiker's Guide to the Galaxy is a comedic science fiction novel that follows the misadventures of Arthur Dent, an ordinary man who is whisked away from Earth just before it is destroyed to make way for an interstellar bypass. Along with his friend Ford Prefect, a researcher for the eponymous guidebook, Arthur travels through space and time, encountering a variety of bizarre creatures and situations. The novel is a hilarious and irreverent take on the sci-fi genre, and has spawned a beloved franchise.", "https://m.media-amazon.com/images/I/51in2RmPhBS._SX328_BO1,204,203,200_.jpg");
INSERT INTO books (book_title, book_author, book_price, book_description, book_image_link)
VALUES ("The Brothers Karamazov", "Fyodor Dostoevsky", 17.00, "The Brothers Karamazov is a philosophical novel that explores the moral and spiritual dilemmas of humanity. The story centers around the Karamazov family, whose patriarch Fyodor has been murdered, and the subsequent investigation and trial of his sons. Through the complex characters and intricate plot, the novel grapples with themes of faith, reason, justice, and redemption. The novel is considered a masterpiece of Russian literature and a seminal work of existentialism.", "https://m.media-amazon.com/images/I/A1dNvQXVPZL.jpg");
INSERT INTO books (book_title, book_author, book_price, book_description, book_image_link)
VALUES ("The Sun Also Rises", "Ernest Hemingway", 8.50, "The Sun Also Rises is a novel that follows a group of expatriates living in Paris in the aftermath of World War I. The story centers around Jake Barnes, a journalist who has been wounded in the war and is impotent as a result. Along with his friends, including the charismatic Brett Ashley, Jake travels to Pamplona, Spain, to witness the bullfights and indulge in the local culture. The novel explores themes of disillusionment, masculinity, and the Lost Generation, and is widely regarded as a classic of modernist literature.", "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781645178569/the-sun-also-rises-and-other-works-9781645178569_hr.jpg");


